// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX9bOMMsvwqhJ7AIrR9XgKvrQa0pXL7W8',
    appId: '1:344734180564:web:f430ef52a08e6b31d38741',
    messagingSenderId: '344734180564',
    projectId: 'androidfinalproject-c2d03',
    authDomain: 'androidfinalproject-c2d03.firebaseapp.com',
    storageBucket: 'androidfinalproject-c2d03.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp_Wku8XbJiuAsw9sf8r4wYYnKIP8DNrA',
    appId: '1:344734180564:android:c41c8acfce634d53d38741',
    messagingSenderId: '344734180564',
    projectId: 'androidfinalproject-c2d03',
    storageBucket: 'androidfinalproject-c2d03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDOviMNDX8vqI4iYi5A67pvtQ17VFa_7U',
    appId: '1:344734180564:ios:054faf9b462855cad38741',
    messagingSenderId: '344734180564',
    projectId: 'androidfinalproject-c2d03',
    storageBucket: 'androidfinalproject-c2d03.firebasestorage.app',
    iosBundleId: 'com.example.androidBigProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDOviMNDX8vqI4iYi5A67pvtQ17VFa_7U',
    appId: '1:344734180564:ios:054faf9b462855cad38741',
    messagingSenderId: '344734180564',
    projectId: 'androidfinalproject-c2d03',
    storageBucket: 'androidfinalproject-c2d03.firebasestorage.app',
    iosBundleId: 'com.example.androidBigProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX9bOMMsvwqhJ7AIrR9XgKvrQa0pXL7W8',
    appId: '1:344734180564:web:4c9e6f78aecc9653d38741',
    messagingSenderId: '344734180564',
    projectId: 'androidfinalproject-c2d03',
    authDomain: 'androidfinalproject-c2d03.firebaseapp.com',
    storageBucket: 'androidfinalproject-c2d03.firebasestorage.app',
  );
}
